# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
#   name: gardener-extension-shoot-networking-problemdetector-admission
#   namespace: kube-system
