seedNamespace: shoot--project--shootname

nameOverride: ""
fullnameOverride: network-problem-detector-controller

replicaCount: 1

images:
  network-problem-detector-controller: any-repo:any-tag

shootClusterSecret: network-problem-detector-controller-kubecfg
podAnnotations: {}

genericTokenKubeconfigSecretName: generic-token-kubeconfig

resources:
  requests:
   cpu: 10m
   memory: 48Mi
  limits:
   memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
# priorityClassName: ""

configuration:
  metricsPort: 10258
  healthProbePort: 10259

