apiVersion: v1
description: A Helm chart to deploy the gardener-extension-shoot-networking-problemdetector-admission runtime related resources
name: admission-shoot-networking-problemdetector-runtime
version: 0.1.0
