//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalProbe) DeepCopyInto(out *AdditionalProbe) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalProbe.
func (in *AdditionalProbe) DeepCopy() *AdditionalProbe {
	if in == nil {
		return nil
	}
	out := new(AdditionalProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.NetworkProblemDetector != nil {
		in, out := &in.NetworkProblemDetector, &out.NetworkProblemDetector
		*out = new(NetworkProblemDetector)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheckConfig != nil {
		in, out := &in.HealthCheckConfig, &out.HealthCheckConfig
		*out = new(configv1alpha1.HealthCheckConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sExporter) DeepCopyInto(out *K8sExporter) {
	*out = *in
	if in.HeartbeatPeriod != nil {
		in, out := &in.HeartbeatPeriod, &out.HeartbeatPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinFailingPeerNodeShare != nil {
		in, out := &in.MinFailingPeerNodeShare, &out.MinFailingPeerNodeShare
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sExporter.
func (in *K8sExporter) DeepCopy() *K8sExporter {
	if in == nil {
		return nil
	}
	out := new(K8sExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProblemDetector) DeepCopyInto(out *NetworkProblemDetector) {
	*out = *in
	if in.DefaultPeriod != nil {
		in, out := &in.DefaultPeriod, &out.DefaultPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxPeerNodes != nil {
		in, out := &in.MaxPeerNodes, &out.MaxPeerNodes
		*out = new(int)
		**out = **in
	}
	if in.IcmpEnabled != nil {
		in, out := &in.IcmpEnabled, &out.IcmpEnabled
		*out = new(bool)
		**out = **in
	}
	if in.K8sExporter != nil {
		in, out := &in.K8sExporter, &out.K8sExporter
		*out = new(K8sExporter)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalProbes != nil {
		in, out := &in.AdditionalProbes, &out.AdditionalProbes
		*out = make([]AdditionalProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProblemDetector.
func (in *NetworkProblemDetector) DeepCopy() *NetworkProblemDetector {
	if in == nil {
		return nil
	}
	out := new(NetworkProblemDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootProviderConfig) DeepCopyInto(out *ShootProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.IcmpEnabled != nil {
		in, out := &in.IcmpEnabled, &out.IcmpEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalProbes != nil {
		in, out := &in.AdditionalProbes, &out.AdditionalProbes
		*out = make([]AdditionalProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootProviderConfig.
func (in *ShootProviderConfig) DeepCopy() *ShootProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ShootProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShootProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
