//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-networking-problemdetector/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalProbe)(nil), (*config.AdditionalProbe)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalProbe_To_config_AdditionalProbe(a.(*AdditionalProbe), b.(*config.AdditionalProbe), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AdditionalProbe)(nil), (*AdditionalProbe)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AdditionalProbe_To_v1alpha1_AdditionalProbe(a.(*config.AdditionalProbe), b.(*AdditionalProbe), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8sExporter)(nil), (*config.K8sExporter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_K8sExporter_To_config_K8sExporter(a.(*K8sExporter), b.(*config.K8sExporter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.K8sExporter)(nil), (*K8sExporter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_K8sExporter_To_v1alpha1_K8sExporter(a.(*config.K8sExporter), b.(*K8sExporter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkProblemDetector)(nil), (*config.NetworkProblemDetector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(a.(*NetworkProblemDetector), b.(*config.NetworkProblemDetector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.NetworkProblemDetector)(nil), (*NetworkProblemDetector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(a.(*config.NetworkProblemDetector), b.(*NetworkProblemDetector), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdditionalProbe_To_config_AdditionalProbe(in *AdditionalProbe, out *config.AdditionalProbe, s conversion.Scope) error {
	*out = *(*config.AdditionalProbe)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_AdditionalProbe_To_config_AdditionalProbe is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalProbe_To_config_AdditionalProbe(in *AdditionalProbe, out *config.AdditionalProbe, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalProbe_To_config_AdditionalProbe(in, out, s)
}

func autoConvert_config_AdditionalProbe_To_v1alpha1_AdditionalProbe(in *config.AdditionalProbe, out *AdditionalProbe, s conversion.Scope) error {
	*out = *(*AdditionalProbe)(unsafe.Pointer(in))
	return nil
}

// Convert_config_AdditionalProbe_To_v1alpha1_AdditionalProbe is an autogenerated conversion function.
func Convert_config_AdditionalProbe_To_v1alpha1_AdditionalProbe(in *config.AdditionalProbe, out *AdditionalProbe, s conversion.Scope) error {
	return autoConvert_config_AdditionalProbe_To_v1alpha1_AdditionalProbe(in, out, s)
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.NetworkProblemDetector = (*config.NetworkProblemDetector)(unsafe.Pointer(in.NetworkProblemDetector))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.NetworkProblemDetector = (*NetworkProblemDetector)(unsafe.Pointer(in.NetworkProblemDetector))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_K8sExporter_To_config_K8sExporter(in *K8sExporter, out *config.K8sExporter, s conversion.Scope) error {
	*out = *(*config.K8sExporter)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_K8sExporter_To_config_K8sExporter is an autogenerated conversion function.
func Convert_v1alpha1_K8sExporter_To_config_K8sExporter(in *K8sExporter, out *config.K8sExporter, s conversion.Scope) error {
	return autoConvert_v1alpha1_K8sExporter_To_config_K8sExporter(in, out, s)
}

func autoConvert_config_K8sExporter_To_v1alpha1_K8sExporter(in *config.K8sExporter, out *K8sExporter, s conversion.Scope) error {
	*out = *(*K8sExporter)(unsafe.Pointer(in))
	return nil
}

// Convert_config_K8sExporter_To_v1alpha1_K8sExporter is an autogenerated conversion function.
func Convert_config_K8sExporter_To_v1alpha1_K8sExporter(in *config.K8sExporter, out *K8sExporter, s conversion.Scope) error {
	return autoConvert_config_K8sExporter_To_v1alpha1_K8sExporter(in, out, s)
}

func autoConvert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in *NetworkProblemDetector, out *config.NetworkProblemDetector, s conversion.Scope) error {
	*out = *(*config.NetworkProblemDetector)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector is an autogenerated conversion function.
func Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in *NetworkProblemDetector, out *config.NetworkProblemDetector, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in, out, s)
}

func autoConvert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in *config.NetworkProblemDetector, out *NetworkProblemDetector, s conversion.Scope) error {
	*out = *(*NetworkProblemDetector)(unsafe.Pointer(in))
	return nil
}

// Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector is an autogenerated conversion function.
func Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in *config.NetworkProblemDetector, out *NetworkProblemDetector, s conversion.Scope) error {
	return autoConvert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in, out, s)
}
