//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-networking-problemdetector/pkg/apis/config"
	healthcheckconfig "github.com/gardener/gardener/extensions/pkg/controller/healthcheck/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/controller/healthcheck/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkProblemDetector)(nil), (*config.NetworkProblemDetector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(a.(*NetworkProblemDetector), b.(*config.NetworkProblemDetector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.NetworkProblemDetector)(nil), (*NetworkProblemDetector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(a.(*config.NetworkProblemDetector), b.(*NetworkProblemDetector), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.NetworkProblemDetector = (*config.NetworkProblemDetector)(unsafe.Pointer(in.NetworkProblemDetector))
	out.HealthCheckConfig = (*healthcheckconfig.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.NetworkProblemDetector = (*NetworkProblemDetector)(unsafe.Pointer(in.NetworkProblemDetector))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in *NetworkProblemDetector, out *config.NetworkProblemDetector, s conversion.Scope) error {
	out.DefaultPeriod = (*v1.Duration)(unsafe.Pointer(in.DefaultPeriod))
	return nil
}

// Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector is an autogenerated conversion function.
func Convert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in *NetworkProblemDetector, out *config.NetworkProblemDetector, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkProblemDetector_To_config_NetworkProblemDetector(in, out, s)
}

func autoConvert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in *config.NetworkProblemDetector, out *NetworkProblemDetector, s conversion.Scope) error {
	out.DefaultPeriod = (*v1.Duration)(unsafe.Pointer(in.DefaultPeriod))
	return nil
}

// Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector is an autogenerated conversion function.
func Convert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in *config.NetworkProblemDetector, out *NetworkProblemDetector, s conversion.Scope) error {
	return autoConvert_config_NetworkProblemDetector_To_v1alpha1_NetworkProblemDetector(in, out, s)
}
