#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

"$(dirname $0)"/hack/set_dependency_version '{"network-problem-detector": ["network-problem-detector-agent", "network-problem-detector-controller"]}'
