#!/usr/bin/env bash

# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

"$(dirname $0)"/hack/set_dependency_version '{"network-problem-detector": ["network-problem-detector-agent", "network-problem-detector-controller"]}'
